#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with special messages for certain numbers.

num=1
while [ $num -le 20 ]
do
  case $num in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo $num
      ;;
  esac
  ((num++))
done
