#!/bin/bash

PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "$PROCESS_NAME is already running."
        exit 1
    fi
    nohup ./manage_my_process &> /dev/null &
    echo $! > "$PID_FILE"
    echo "$PROCESS_NAME started"
}

stop() {
    if [ ! -f "$PID_FILE" ]; then
        echo "$PROCESS_NAME is not running."
        exit 1
    fi
    kill $(cat "$PID_FILE")
    rm -f "$PID_FILE"
    echo "$PROCESS_NAME stopped"
}

restart() {
    stop
    start
    echo "$PROCESS_NAME restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
